# Generated by Django 2.2.8 on 2020-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='slug',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
